//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Menhely.MenhelyServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Allat", Namespace="http://schemas.datacontract.org/2004/07/Menhely", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class Allat : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AlFajField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Menhely.MenhelyServiceReference.OrokbefogadasAllapot AllapotField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Menhely.MenhelyServiceReference.AllatFaj FajField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] GondozasokField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Menhely.MenhelyServiceReference.Gondozo[] GondozokField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Menhely.MenhelyServiceReference.Ketrec KetrecField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int KorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LeirasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NevField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Menhely.MenhelyServiceReference.Orokbefogado OrokbefogadoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AlFaj {
            get {
                return this.AlFajField;
            }
            set {
                if ((object.ReferenceEquals(this.AlFajField, value) != true)) {
                    this.AlFajField = value;
                    this.RaisePropertyChanged("AlFaj");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Menhely.MenhelyServiceReference.OrokbefogadasAllapot Allapot {
            get {
                return this.AllapotField;
            }
            set {
                if ((this.AllapotField.Equals(value) != true)) {
                    this.AllapotField = value;
                    this.RaisePropertyChanged("Allapot");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Menhely.MenhelyServiceReference.AllatFaj Faj {
            get {
                return this.FajField;
            }
            set {
                if ((this.FajField.Equals(value) != true)) {
                    this.FajField = value;
                    this.RaisePropertyChanged("Faj");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] Gondozasok {
            get {
                return this.GondozasokField;
            }
            set {
                if ((object.ReferenceEquals(this.GondozasokField, value) != true)) {
                    this.GondozasokField = value;
                    this.RaisePropertyChanged("Gondozasok");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Menhely.MenhelyServiceReference.Gondozo[] Gondozok {
            get {
                return this.GondozokField;
            }
            set {
                if ((object.ReferenceEquals(this.GondozokField, value) != true)) {
                    this.GondozokField = value;
                    this.RaisePropertyChanged("Gondozok");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Menhely.MenhelyServiceReference.Ketrec Ketrec {
            get {
                return this.KetrecField;
            }
            set {
                if ((object.ReferenceEquals(this.KetrecField, value) != true)) {
                    this.KetrecField = value;
                    this.RaisePropertyChanged("Ketrec");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Kor {
            get {
                return this.KorField;
            }
            set {
                if ((this.KorField.Equals(value) != true)) {
                    this.KorField = value;
                    this.RaisePropertyChanged("Kor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Leiras {
            get {
                return this.LeirasField;
            }
            set {
                if ((object.ReferenceEquals(this.LeirasField, value) != true)) {
                    this.LeirasField = value;
                    this.RaisePropertyChanged("Leiras");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nev {
            get {
                return this.NevField;
            }
            set {
                if ((object.ReferenceEquals(this.NevField, value) != true)) {
                    this.NevField = value;
                    this.RaisePropertyChanged("Nev");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Menhely.MenhelyServiceReference.Orokbefogado Orokbefogado {
            get {
                return this.OrokbefogadoField;
            }
            set {
                if ((object.ReferenceEquals(this.OrokbefogadoField, value) != true)) {
                    this.OrokbefogadoField = value;
                    this.RaisePropertyChanged("Orokbefogado");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Ketrec", Namespace="http://schemas.datacontract.org/2004/07/Menhely", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class Ketrec : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Menhely.MenhelyServiceReference.Allat[] AllatokField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Menhely.MenhelyServiceReference.AllatFaj FajField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Menhely.MenhelyServiceReference.Telephely HelyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int KetrecIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MeretField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Menhely.MenhelyServiceReference.Allat[] Allatok {
            get {
                return this.AllatokField;
            }
            set {
                if ((object.ReferenceEquals(this.AllatokField, value) != true)) {
                    this.AllatokField = value;
                    this.RaisePropertyChanged("Allatok");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Menhely.MenhelyServiceReference.AllatFaj Faj {
            get {
                return this.FajField;
            }
            set {
                if ((this.FajField.Equals(value) != true)) {
                    this.FajField = value;
                    this.RaisePropertyChanged("Faj");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Menhely.MenhelyServiceReference.Telephely Hely {
            get {
                return this.HelyField;
            }
            set {
                if ((object.ReferenceEquals(this.HelyField, value) != true)) {
                    this.HelyField = value;
                    this.RaisePropertyChanged("Hely");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int KetrecID {
            get {
                return this.KetrecIDField;
            }
            set {
                if ((this.KetrecIDField.Equals(value) != true)) {
                    this.KetrecIDField = value;
                    this.RaisePropertyChanged("KetrecID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Meret {
            get {
                return this.MeretField;
            }
            set {
                if ((this.MeretField.Equals(value) != true)) {
                    this.MeretField = value;
                    this.RaisePropertyChanged("Meret");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Orokbefogado", Namespace="http://schemas.datacontract.org/2004/07/Menhely", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class Orokbefogado : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AdomanyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string JelszoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NevField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Menhely.MenhelyServiceReference.Allat[] OrokbeFogadandoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime UtolsoCselekvesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Adomany {
            get {
                return this.AdomanyField;
            }
            set {
                if ((this.AdomanyField.Equals(value) != true)) {
                    this.AdomanyField = value;
                    this.RaisePropertyChanged("Adomany");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Jelszo {
            get {
                return this.JelszoField;
            }
            set {
                if ((object.ReferenceEquals(this.JelszoField, value) != true)) {
                    this.JelszoField = value;
                    this.RaisePropertyChanged("Jelszo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nev {
            get {
                return this.NevField;
            }
            set {
                if ((object.ReferenceEquals(this.NevField, value) != true)) {
                    this.NevField = value;
                    this.RaisePropertyChanged("Nev");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Menhely.MenhelyServiceReference.Allat[] OrokbeFogadando {
            get {
                return this.OrokbeFogadandoField;
            }
            set {
                if ((object.ReferenceEquals(this.OrokbeFogadandoField, value) != true)) {
                    this.OrokbeFogadandoField = value;
                    this.RaisePropertyChanged("OrokbeFogadando");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime UtolsoCselekves {
            get {
                return this.UtolsoCselekvesField;
            }
            set {
                if ((this.UtolsoCselekvesField.Equals(value) != true)) {
                    this.UtolsoCselekvesField = value;
                    this.RaisePropertyChanged("UtolsoCselekves");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OrokbefogadasAllapot", Namespace="http://schemas.datacontract.org/2004/07/Menhely")]
    public enum OrokbefogadasAllapot : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Szabad = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Foglalt = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ÖrökbeAdva = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AllatFaj", Namespace="http://schemas.datacontract.org/2004/07/Menhely")]
    public enum AllatFaj : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Kutya = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Macska = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Róka = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Süni = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Egyéb = 4,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Gondozo", Namespace="http://schemas.datacontract.org/2004/07/Menhely", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class Gondozo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Menhely.MenhelyServiceReference.GondozoBeosztas BeosztasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Menhely.MenhelyServiceReference.Allat[] GondozottAllatokField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string JelszoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Menhely.MenhelyServiceReference.Telephely[] MunkahelyekField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NevField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime UtolsoCselekvesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Menhely.MenhelyServiceReference.GondozoBeosztas Beosztas {
            get {
                return this.BeosztasField;
            }
            set {
                if ((this.BeosztasField.Equals(value) != true)) {
                    this.BeosztasField = value;
                    this.RaisePropertyChanged("Beosztas");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Menhely.MenhelyServiceReference.Allat[] GondozottAllatok {
            get {
                return this.GondozottAllatokField;
            }
            set {
                if ((object.ReferenceEquals(this.GondozottAllatokField, value) != true)) {
                    this.GondozottAllatokField = value;
                    this.RaisePropertyChanged("GondozottAllatok");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Jelszo {
            get {
                return this.JelszoField;
            }
            set {
                if ((object.ReferenceEquals(this.JelszoField, value) != true)) {
                    this.JelszoField = value;
                    this.RaisePropertyChanged("Jelszo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Menhely.MenhelyServiceReference.Telephely[] Munkahelyek {
            get {
                return this.MunkahelyekField;
            }
            set {
                if ((object.ReferenceEquals(this.MunkahelyekField, value) != true)) {
                    this.MunkahelyekField = value;
                    this.RaisePropertyChanged("Munkahelyek");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nev {
            get {
                return this.NevField;
            }
            set {
                if ((object.ReferenceEquals(this.NevField, value) != true)) {
                    this.NevField = value;
                    this.RaisePropertyChanged("Nev");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime UtolsoCselekves {
            get {
                return this.UtolsoCselekvesField;
            }
            set {
                if ((this.UtolsoCselekvesField.Equals(value) != true)) {
                    this.UtolsoCselekvesField = value;
                    this.RaisePropertyChanged("UtolsoCselekves");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GondozoBeosztas", Namespace="http://schemas.datacontract.org/2004/07/Menhely")]
    public enum GondozoBeosztas : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Adminisztrátor = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Gondozó = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Befogó = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Telephely", Namespace="http://schemas.datacontract.org/2004/07/Menhely", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class Telephely : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CimField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Menhely.MenhelyServiceReference.Gondozo[] DolgozokField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Menhely.MenhelyServiceReference.Ketrec[] KetrecekField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cim {
            get {
                return this.CimField;
            }
            set {
                if ((object.ReferenceEquals(this.CimField, value) != true)) {
                    this.CimField = value;
                    this.RaisePropertyChanged("Cim");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Menhely.MenhelyServiceReference.Gondozo[] Dolgozok {
            get {
                return this.DolgozokField;
            }
            set {
                if ((object.ReferenceEquals(this.DolgozokField, value) != true)) {
                    this.DolgozokField = value;
                    this.RaisePropertyChanged("Dolgozok");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Menhely.MenhelyServiceReference.Ketrec[] Ketrecek {
            get {
                return this.KetrecekField;
            }
            set {
                if ((object.ReferenceEquals(this.KetrecekField, value) != true)) {
                    this.KetrecekField = value;
                    this.RaisePropertyChanged("Ketrecek");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MenhelyServiceReference.IAllatKezelo")]
    public interface IAllatKezelo {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAllatKezelo/AllatMasikKetrecbe", ReplyAction="http://tempuri.org/IAllatKezelo/AllatMasikKetrecbeResponse")]
        void AllatMasikKetrecbe(Menhely.MenhelyServiceReference.Allat allat, Menhely.MenhelyServiceReference.Ketrec hova);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAllatKezelo/AllatMasikKetrecbe", ReplyAction="http://tempuri.org/IAllatKezelo/AllatMasikKetrecbeResponse")]
        System.Threading.Tasks.Task AllatMasikKetrecbeAsync(Menhely.MenhelyServiceReference.Allat allat, Menhely.MenhelyServiceReference.Ketrec hova);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAllatKezelo/AllatListazas", ReplyAction="http://tempuri.org/IAllatKezelo/AllatListazasResponse")]
        Menhely.MenhelyServiceReference.Allat[] AllatListazas();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAllatKezelo/AllatListazas", ReplyAction="http://tempuri.org/IAllatKezelo/AllatListazasResponse")]
        System.Threading.Tasks.Task<Menhely.MenhelyServiceReference.Allat[]> AllatListazasAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAllatKezelo/AllatListazasEgy", ReplyAction="http://tempuri.org/IAllatKezelo/AllatListazasEgyResponse")]
        Menhely.MenhelyServiceReference.Allat[] AllatListazasEgy(string nev);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAllatKezelo/AllatListazasEgy", ReplyAction="http://tempuri.org/IAllatKezelo/AllatListazasEgyResponse")]
        System.Threading.Tasks.Task<Menhely.MenhelyServiceReference.Allat[]> AllatListazasEgyAsync(string nev);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAllatKezelo/AllatModositas", ReplyAction="http://tempuri.org/IAllatKezelo/AllatModositasResponse")]
        void AllatModositas(Menhely.MenhelyServiceReference.Allat allat, Menhely.MenhelyServiceReference.Gondozo gondozo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAllatKezelo/AllatModositas", ReplyAction="http://tempuri.org/IAllatKezelo/AllatModositasResponse")]
        System.Threading.Tasks.Task AllatModositasAsync(Menhely.MenhelyServiceReference.Allat allat, Menhely.MenhelyServiceReference.Gondozo gondozo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAllatKezelo/AllatTorlese", ReplyAction="http://tempuri.org/IAllatKezelo/AllatTorleseResponse")]
        void AllatTorlese(Menhely.MenhelyServiceReference.Allat allat, Menhely.MenhelyServiceReference.Gondozo gondozo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAllatKezelo/AllatTorlese", ReplyAction="http://tempuri.org/IAllatKezelo/AllatTorleseResponse")]
        System.Threading.Tasks.Task AllatTorleseAsync(Menhely.MenhelyServiceReference.Allat allat, Menhely.MenhelyServiceReference.Gondozo gondozo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAllatKezelo/AllatGondozas", ReplyAction="http://tempuri.org/IAllatKezelo/AllatGondozasResponse")]
        void AllatGondozas(Menhely.MenhelyServiceReference.Allat allat, Menhely.MenhelyServiceReference.Gondozo gondozo, string jegyzokonyv);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAllatKezelo/AllatGondozas", ReplyAction="http://tempuri.org/IAllatKezelo/AllatGondozasResponse")]
        System.Threading.Tasks.Task AllatGondozasAsync(Menhely.MenhelyServiceReference.Allat allat, Menhely.MenhelyServiceReference.Gondozo gondozo, string jegyzokonyv);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAllatKezelo/AllatFelvetel", ReplyAction="http://tempuri.org/IAllatKezelo/AllatFelvetelResponse")]
        void AllatFelvetel(string nev, string leiras, int kor, Menhely.MenhelyServiceReference.AllatFaj faj, string alFaj, Menhely.MenhelyServiceReference.Ketrec ketrec, Menhely.MenhelyServiceReference.Gondozo gondozo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAllatKezelo/AllatFelvetel", ReplyAction="http://tempuri.org/IAllatKezelo/AllatFelvetelResponse")]
        System.Threading.Tasks.Task AllatFelvetelAsync(string nev, string leiras, int kor, Menhely.MenhelyServiceReference.AllatFaj faj, string alFaj, Menhely.MenhelyServiceReference.Ketrec ketrec, Menhely.MenhelyServiceReference.Gondozo gondozo);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAllatKezeloChannel : Menhely.MenhelyServiceReference.IAllatKezelo, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AllatKezeloClient : System.ServiceModel.ClientBase<Menhely.MenhelyServiceReference.IAllatKezelo>, Menhely.MenhelyServiceReference.IAllatKezelo {
        
        public AllatKezeloClient() {
        }
        
        public AllatKezeloClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AllatKezeloClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AllatKezeloClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AllatKezeloClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void AllatMasikKetrecbe(Menhely.MenhelyServiceReference.Allat allat, Menhely.MenhelyServiceReference.Ketrec hova) {
            base.Channel.AllatMasikKetrecbe(allat, hova);
        }
        
        public System.Threading.Tasks.Task AllatMasikKetrecbeAsync(Menhely.MenhelyServiceReference.Allat allat, Menhely.MenhelyServiceReference.Ketrec hova) {
            return base.Channel.AllatMasikKetrecbeAsync(allat, hova);
        }
        
        public Menhely.MenhelyServiceReference.Allat[] AllatListazas() {
            return base.Channel.AllatListazas();
        }
        
        public System.Threading.Tasks.Task<Menhely.MenhelyServiceReference.Allat[]> AllatListazasAsync() {
            return base.Channel.AllatListazasAsync();
        }
        
        public Menhely.MenhelyServiceReference.Allat[] AllatListazasEgy(string nev) {
            return base.Channel.AllatListazasEgy(nev);
        }
        
        public System.Threading.Tasks.Task<Menhely.MenhelyServiceReference.Allat[]> AllatListazasEgyAsync(string nev) {
            return base.Channel.AllatListazasEgyAsync(nev);
        }
        
        public void AllatModositas(Menhely.MenhelyServiceReference.Allat allat, Menhely.MenhelyServiceReference.Gondozo gondozo) {
            base.Channel.AllatModositas(allat, gondozo);
        }
        
        public System.Threading.Tasks.Task AllatModositasAsync(Menhely.MenhelyServiceReference.Allat allat, Menhely.MenhelyServiceReference.Gondozo gondozo) {
            return base.Channel.AllatModositasAsync(allat, gondozo);
        }
        
        public void AllatTorlese(Menhely.MenhelyServiceReference.Allat allat, Menhely.MenhelyServiceReference.Gondozo gondozo) {
            base.Channel.AllatTorlese(allat, gondozo);
        }
        
        public System.Threading.Tasks.Task AllatTorleseAsync(Menhely.MenhelyServiceReference.Allat allat, Menhely.MenhelyServiceReference.Gondozo gondozo) {
            return base.Channel.AllatTorleseAsync(allat, gondozo);
        }
        
        public void AllatGondozas(Menhely.MenhelyServiceReference.Allat allat, Menhely.MenhelyServiceReference.Gondozo gondozo, string jegyzokonyv) {
            base.Channel.AllatGondozas(allat, gondozo, jegyzokonyv);
        }
        
        public System.Threading.Tasks.Task AllatGondozasAsync(Menhely.MenhelyServiceReference.Allat allat, Menhely.MenhelyServiceReference.Gondozo gondozo, string jegyzokonyv) {
            return base.Channel.AllatGondozasAsync(allat, gondozo, jegyzokonyv);
        }
        
        public void AllatFelvetel(string nev, string leiras, int kor, Menhely.MenhelyServiceReference.AllatFaj faj, string alFaj, Menhely.MenhelyServiceReference.Ketrec ketrec, Menhely.MenhelyServiceReference.Gondozo gondozo) {
            base.Channel.AllatFelvetel(nev, leiras, kor, faj, alFaj, ketrec, gondozo);
        }
        
        public System.Threading.Tasks.Task AllatFelvetelAsync(string nev, string leiras, int kor, Menhely.MenhelyServiceReference.AllatFaj faj, string alFaj, Menhely.MenhelyServiceReference.Ketrec ketrec, Menhely.MenhelyServiceReference.Gondozo gondozo) {
            return base.Channel.AllatFelvetelAsync(nev, leiras, kor, faj, alFaj, ketrec, gondozo);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MenhelyServiceReference.IGondozoKezelo")]
    public interface IGondozoKezelo {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGondozoKezelo/Bejelenkezes", ReplyAction="http://tempuri.org/IGondozoKezelo/BejelenkezesResponse")]
        Menhely.MenhelyServiceReference.Gondozo Bejelenkezes(string nev, string jelszo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGondozoKezelo/Bejelenkezes", ReplyAction="http://tempuri.org/IGondozoKezelo/BejelenkezesResponse")]
        System.Threading.Tasks.Task<Menhely.MenhelyServiceReference.Gondozo> BejelenkezesAsync(string nev, string jelszo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGondozoKezelo/GondozoListazas", ReplyAction="http://tempuri.org/IGondozoKezelo/GondozoListazasResponse")]
        Menhely.MenhelyServiceReference.Gondozo[] GondozoListazas();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGondozoKezelo/GondozoListazas", ReplyAction="http://tempuri.org/IGondozoKezelo/GondozoListazasResponse")]
        System.Threading.Tasks.Task<Menhely.MenhelyServiceReference.Gondozo[]> GondozoListazasAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGondozoKezelo/GondozoListazasEgy", ReplyAction="http://tempuri.org/IGondozoKezelo/GondozoListazasEgyResponse")]
        Menhely.MenhelyServiceReference.Gondozo[] GondozoListazasEgy(string nev);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGondozoKezelo/GondozoListazasEgy", ReplyAction="http://tempuri.org/IGondozoKezelo/GondozoListazasEgyResponse")]
        System.Threading.Tasks.Task<Menhely.MenhelyServiceReference.Gondozo[]> GondozoListazasEgyAsync(string nev);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGondozoKezelo/GondozoModositas", ReplyAction="http://tempuri.org/IGondozoKezelo/GondozoModositasResponse")]
        void GondozoModositas(Menhely.MenhelyServiceReference.Gondozo gondozo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGondozoKezelo/GondozoModositas", ReplyAction="http://tempuri.org/IGondozoKezelo/GondozoModositasResponse")]
        System.Threading.Tasks.Task GondozoModositasAsync(Menhely.MenhelyServiceReference.Gondozo gondozo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGondozoKezelo/GondozoLetrehozas", ReplyAction="http://tempuri.org/IGondozoKezelo/GondozoLetrehozasResponse")]
        void GondozoLetrehozas(string nev, Menhely.MenhelyServiceReference.GondozoBeosztas beosztas, string jelszo, Menhely.MenhelyServiceReference.Telephely munkahely);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGondozoKezelo/GondozoLetrehozas", ReplyAction="http://tempuri.org/IGondozoKezelo/GondozoLetrehozasResponse")]
        System.Threading.Tasks.Task GondozoLetrehozasAsync(string nev, Menhely.MenhelyServiceReference.GondozoBeosztas beosztas, string jelszo, Menhely.MenhelyServiceReference.Telephely munkahely);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGondozoKezelo/GondozoTorles", ReplyAction="http://tempuri.org/IGondozoKezelo/GondozoTorlesResponse")]
        void GondozoTorles(Menhely.MenhelyServiceReference.Gondozo gondozo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGondozoKezelo/GondozoTorles", ReplyAction="http://tempuri.org/IGondozoKezelo/GondozoTorlesResponse")]
        System.Threading.Tasks.Task GondozoTorlesAsync(Menhely.MenhelyServiceReference.Gondozo gondozo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGondozoKezelo/BejelentkezesEllenorzesGondozo", ReplyAction="http://tempuri.org/IGondozoKezelo/BejelentkezesEllenorzesGondozoResponse")]
        bool BejelentkezesEllenorzesGondozo(Menhely.MenhelyServiceReference.Gondozo gondozo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGondozoKezelo/BejelentkezesEllenorzesGondozo", ReplyAction="http://tempuri.org/IGondozoKezelo/BejelentkezesEllenorzesGondozoResponse")]
        System.Threading.Tasks.Task<bool> BejelentkezesEllenorzesGondozoAsync(Menhely.MenhelyServiceReference.Gondozo gondozo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGondozoKezelo/GondozottAllatHozzaadas", ReplyAction="http://tempuri.org/IGondozoKezelo/GondozottAllatHozzaadasResponse")]
        void GondozottAllatHozzaadas(Menhely.MenhelyServiceReference.Gondozo gondozo, Menhely.MenhelyServiceReference.Allat allat);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGondozoKezelo/GondozottAllatHozzaadas", ReplyAction="http://tempuri.org/IGondozoKezelo/GondozottAllatHozzaadasResponse")]
        System.Threading.Tasks.Task GondozottAllatHozzaadasAsync(Menhely.MenhelyServiceReference.Gondozo gondozo, Menhely.MenhelyServiceReference.Allat allat);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGondozoKezelo/TelephelyGondozohozAdas", ReplyAction="http://tempuri.org/IGondozoKezelo/TelephelyGondozohozAdasResponse")]
        void TelephelyGondozohozAdas(Menhely.MenhelyServiceReference.Gondozo gondozo, Menhely.MenhelyServiceReference.Telephely telephely);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGondozoKezelo/TelephelyGondozohozAdas", ReplyAction="http://tempuri.org/IGondozoKezelo/TelephelyGondozohozAdasResponse")]
        System.Threading.Tasks.Task TelephelyGondozohozAdasAsync(Menhely.MenhelyServiceReference.Gondozo gondozo, Menhely.MenhelyServiceReference.Telephely telephely);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGondozoKezelo/GondozottAllatEltavolitas", ReplyAction="http://tempuri.org/IGondozoKezelo/GondozottAllatEltavolitasResponse")]
        void GondozottAllatEltavolitas(Menhely.MenhelyServiceReference.Gondozo gondozo, Menhely.MenhelyServiceReference.Allat allat);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGondozoKezelo/GondozottAllatEltavolitas", ReplyAction="http://tempuri.org/IGondozoKezelo/GondozottAllatEltavolitasResponse")]
        System.Threading.Tasks.Task GondozottAllatEltavolitasAsync(Menhely.MenhelyServiceReference.Gondozo gondozo, Menhely.MenhelyServiceReference.Allat allat);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGondozoKezelo/TelephelyGondozotolLevetel", ReplyAction="http://tempuri.org/IGondozoKezelo/TelephelyGondozotolLevetelResponse")]
        void TelephelyGondozotolLevetel(Menhely.MenhelyServiceReference.Gondozo gondozo, Menhely.MenhelyServiceReference.Telephely telephely);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGondozoKezelo/TelephelyGondozotolLevetel", ReplyAction="http://tempuri.org/IGondozoKezelo/TelephelyGondozotolLevetelResponse")]
        System.Threading.Tasks.Task TelephelyGondozotolLevetelAsync(Menhely.MenhelyServiceReference.Gondozo gondozo, Menhely.MenhelyServiceReference.Telephely telephely);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGondozoKezeloChannel : Menhely.MenhelyServiceReference.IGondozoKezelo, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GondozoKezeloClient : System.ServiceModel.ClientBase<Menhely.MenhelyServiceReference.IGondozoKezelo>, Menhely.MenhelyServiceReference.IGondozoKezelo {
        
        public GondozoKezeloClient() {
        }
        
        public GondozoKezeloClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GondozoKezeloClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GondozoKezeloClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GondozoKezeloClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Menhely.MenhelyServiceReference.Gondozo Bejelenkezes(string nev, string jelszo) {
            return base.Channel.Bejelenkezes(nev, jelszo);
        }
        
        public System.Threading.Tasks.Task<Menhely.MenhelyServiceReference.Gondozo> BejelenkezesAsync(string nev, string jelszo) {
            return base.Channel.BejelenkezesAsync(nev, jelszo);
        }
        
        public Menhely.MenhelyServiceReference.Gondozo[] GondozoListazas() {
            return base.Channel.GondozoListazas();
        }
        
        public System.Threading.Tasks.Task<Menhely.MenhelyServiceReference.Gondozo[]> GondozoListazasAsync() {
            return base.Channel.GondozoListazasAsync();
        }
        
        public Menhely.MenhelyServiceReference.Gondozo[] GondozoListazasEgy(string nev) {
            return base.Channel.GondozoListazasEgy(nev);
        }
        
        public System.Threading.Tasks.Task<Menhely.MenhelyServiceReference.Gondozo[]> GondozoListazasEgyAsync(string nev) {
            return base.Channel.GondozoListazasEgyAsync(nev);
        }
        
        public void GondozoModositas(Menhely.MenhelyServiceReference.Gondozo gondozo) {
            base.Channel.GondozoModositas(gondozo);
        }
        
        public System.Threading.Tasks.Task GondozoModositasAsync(Menhely.MenhelyServiceReference.Gondozo gondozo) {
            return base.Channel.GondozoModositasAsync(gondozo);
        }
        
        public void GondozoLetrehozas(string nev, Menhely.MenhelyServiceReference.GondozoBeosztas beosztas, string jelszo, Menhely.MenhelyServiceReference.Telephely munkahely) {
            base.Channel.GondozoLetrehozas(nev, beosztas, jelszo, munkahely);
        }
        
        public System.Threading.Tasks.Task GondozoLetrehozasAsync(string nev, Menhely.MenhelyServiceReference.GondozoBeosztas beosztas, string jelszo, Menhely.MenhelyServiceReference.Telephely munkahely) {
            return base.Channel.GondozoLetrehozasAsync(nev, beosztas, jelszo, munkahely);
        }
        
        public void GondozoTorles(Menhely.MenhelyServiceReference.Gondozo gondozo) {
            base.Channel.GondozoTorles(gondozo);
        }
        
        public System.Threading.Tasks.Task GondozoTorlesAsync(Menhely.MenhelyServiceReference.Gondozo gondozo) {
            return base.Channel.GondozoTorlesAsync(gondozo);
        }
        
        public bool BejelentkezesEllenorzesGondozo(Menhely.MenhelyServiceReference.Gondozo gondozo) {
            return base.Channel.BejelentkezesEllenorzesGondozo(gondozo);
        }
        
        public System.Threading.Tasks.Task<bool> BejelentkezesEllenorzesGondozoAsync(Menhely.MenhelyServiceReference.Gondozo gondozo) {
            return base.Channel.BejelentkezesEllenorzesGondozoAsync(gondozo);
        }
        
        public void GondozottAllatHozzaadas(Menhely.MenhelyServiceReference.Gondozo gondozo, Menhely.MenhelyServiceReference.Allat allat) {
            base.Channel.GondozottAllatHozzaadas(gondozo, allat);
        }
        
        public System.Threading.Tasks.Task GondozottAllatHozzaadasAsync(Menhely.MenhelyServiceReference.Gondozo gondozo, Menhely.MenhelyServiceReference.Allat allat) {
            return base.Channel.GondozottAllatHozzaadasAsync(gondozo, allat);
        }
        
        public void TelephelyGondozohozAdas(Menhely.MenhelyServiceReference.Gondozo gondozo, Menhely.MenhelyServiceReference.Telephely telephely) {
            base.Channel.TelephelyGondozohozAdas(gondozo, telephely);
        }
        
        public System.Threading.Tasks.Task TelephelyGondozohozAdasAsync(Menhely.MenhelyServiceReference.Gondozo gondozo, Menhely.MenhelyServiceReference.Telephely telephely) {
            return base.Channel.TelephelyGondozohozAdasAsync(gondozo, telephely);
        }
        
        public void GondozottAllatEltavolitas(Menhely.MenhelyServiceReference.Gondozo gondozo, Menhely.MenhelyServiceReference.Allat allat) {
            base.Channel.GondozottAllatEltavolitas(gondozo, allat);
        }
        
        public System.Threading.Tasks.Task GondozottAllatEltavolitasAsync(Menhely.MenhelyServiceReference.Gondozo gondozo, Menhely.MenhelyServiceReference.Allat allat) {
            return base.Channel.GondozottAllatEltavolitasAsync(gondozo, allat);
        }
        
        public void TelephelyGondozotolLevetel(Menhely.MenhelyServiceReference.Gondozo gondozo, Menhely.MenhelyServiceReference.Telephely telephely) {
            base.Channel.TelephelyGondozotolLevetel(gondozo, telephely);
        }
        
        public System.Threading.Tasks.Task TelephelyGondozotolLevetelAsync(Menhely.MenhelyServiceReference.Gondozo gondozo, Menhely.MenhelyServiceReference.Telephely telephely) {
            return base.Channel.TelephelyGondozotolLevetelAsync(gondozo, telephely);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MenhelyServiceReference.IOrokbefogadoKezelo")]
    public interface IOrokbefogadoKezelo {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrokbefogadoKezelo/Adomanyozas", ReplyAction="http://tempuri.org/IOrokbefogadoKezelo/AdomanyozasResponse")]
        void Adomanyozas(Menhely.MenhelyServiceReference.Orokbefogado orokbefogado, int adomanyOsszeg);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrokbefogadoKezelo/Adomanyozas", ReplyAction="http://tempuri.org/IOrokbefogadoKezelo/AdomanyozasResponse")]
        System.Threading.Tasks.Task AdomanyozasAsync(Menhely.MenhelyServiceReference.Orokbefogado orokbefogado, int adomanyOsszeg);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrokbefogadoKezelo/Bejelentkezes", ReplyAction="http://tempuri.org/IOrokbefogadoKezelo/BejelentkezesResponse")]
        Menhely.MenhelyServiceReference.Orokbefogado Bejelentkezes(string nev, string jelszo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrokbefogadoKezelo/Bejelentkezes", ReplyAction="http://tempuri.org/IOrokbefogadoKezelo/BejelentkezesResponse")]
        System.Threading.Tasks.Task<Menhely.MenhelyServiceReference.Orokbefogado> BejelentkezesAsync(string nev, string jelszo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrokbefogadoKezelo/BejelentkezesEllenorzesOrokbefogado", ReplyAction="http://tempuri.org/IOrokbefogadoKezelo/BejelentkezesEllenorzesOrokbefogadoRespons" +
            "e")]
        bool BejelentkezesEllenorzesOrokbefogado(Menhely.MenhelyServiceReference.Orokbefogado orokbefogado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrokbefogadoKezelo/BejelentkezesEllenorzesOrokbefogado", ReplyAction="http://tempuri.org/IOrokbefogadoKezelo/BejelentkezesEllenorzesOrokbefogadoRespons" +
            "e")]
        System.Threading.Tasks.Task<bool> BejelentkezesEllenorzesOrokbefogadoAsync(Menhely.MenhelyServiceReference.Orokbefogado orokbefogado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrokbefogadoKezelo/Regisztracio", ReplyAction="http://tempuri.org/IOrokbefogadoKezelo/RegisztracioResponse")]
        bool Regisztracio(string nev, string jelszo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrokbefogadoKezelo/Regisztracio", ReplyAction="http://tempuri.org/IOrokbefogadoKezelo/RegisztracioResponse")]
        System.Threading.Tasks.Task<bool> RegisztracioAsync(string nev, string jelszo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrokbefogadoKezelo/OrokbefogadoListazas", ReplyAction="http://tempuri.org/IOrokbefogadoKezelo/OrokbefogadoListazasResponse")]
        Menhely.MenhelyServiceReference.Orokbefogado[] OrokbefogadoListazas();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrokbefogadoKezelo/OrokbefogadoListazas", ReplyAction="http://tempuri.org/IOrokbefogadoKezelo/OrokbefogadoListazasResponse")]
        System.Threading.Tasks.Task<Menhely.MenhelyServiceReference.Orokbefogado[]> OrokbefogadoListazasAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrokbefogadoKezelo/OrokbefogadoListazasEgy", ReplyAction="http://tempuri.org/IOrokbefogadoKezelo/OrokbefogadoListazasEgyResponse")]
        Menhely.MenhelyServiceReference.Orokbefogado[] OrokbefogadoListazasEgy(string nev);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrokbefogadoKezelo/OrokbefogadoListazasEgy", ReplyAction="http://tempuri.org/IOrokbefogadoKezelo/OrokbefogadoListazasEgyResponse")]
        System.Threading.Tasks.Task<Menhely.MenhelyServiceReference.Orokbefogado[]> OrokbefogadoListazasEgyAsync(string nev);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IOrokbefogadoKezeloChannel : Menhely.MenhelyServiceReference.IOrokbefogadoKezelo, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OrokbefogadoKezeloClient : System.ServiceModel.ClientBase<Menhely.MenhelyServiceReference.IOrokbefogadoKezelo>, Menhely.MenhelyServiceReference.IOrokbefogadoKezelo {
        
        public OrokbefogadoKezeloClient() {
        }
        
        public OrokbefogadoKezeloClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public OrokbefogadoKezeloClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OrokbefogadoKezeloClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OrokbefogadoKezeloClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void Adomanyozas(Menhely.MenhelyServiceReference.Orokbefogado orokbefogado, int adomanyOsszeg) {
            base.Channel.Adomanyozas(orokbefogado, adomanyOsszeg);
        }
        
        public System.Threading.Tasks.Task AdomanyozasAsync(Menhely.MenhelyServiceReference.Orokbefogado orokbefogado, int adomanyOsszeg) {
            return base.Channel.AdomanyozasAsync(orokbefogado, adomanyOsszeg);
        }
        
        public Menhely.MenhelyServiceReference.Orokbefogado Bejelentkezes(string nev, string jelszo) {
            return base.Channel.Bejelentkezes(nev, jelszo);
        }
        
        public System.Threading.Tasks.Task<Menhely.MenhelyServiceReference.Orokbefogado> BejelentkezesAsync(string nev, string jelszo) {
            return base.Channel.BejelentkezesAsync(nev, jelszo);
        }
        
        public bool BejelentkezesEllenorzesOrokbefogado(Menhely.MenhelyServiceReference.Orokbefogado orokbefogado) {
            return base.Channel.BejelentkezesEllenorzesOrokbefogado(orokbefogado);
        }
        
        public System.Threading.Tasks.Task<bool> BejelentkezesEllenorzesOrokbefogadoAsync(Menhely.MenhelyServiceReference.Orokbefogado orokbefogado) {
            return base.Channel.BejelentkezesEllenorzesOrokbefogadoAsync(orokbefogado);
        }
        
        public bool Regisztracio(string nev, string jelszo) {
            return base.Channel.Regisztracio(nev, jelszo);
        }
        
        public System.Threading.Tasks.Task<bool> RegisztracioAsync(string nev, string jelszo) {
            return base.Channel.RegisztracioAsync(nev, jelszo);
        }
        
        public Menhely.MenhelyServiceReference.Orokbefogado[] OrokbefogadoListazas() {
            return base.Channel.OrokbefogadoListazas();
        }
        
        public System.Threading.Tasks.Task<Menhely.MenhelyServiceReference.Orokbefogado[]> OrokbefogadoListazasAsync() {
            return base.Channel.OrokbefogadoListazasAsync();
        }
        
        public Menhely.MenhelyServiceReference.Orokbefogado[] OrokbefogadoListazasEgy(string nev) {
            return base.Channel.OrokbefogadoListazasEgy(nev);
        }
        
        public System.Threading.Tasks.Task<Menhely.MenhelyServiceReference.Orokbefogado[]> OrokbefogadoListazasEgyAsync(string nev) {
            return base.Channel.OrokbefogadoListazasEgyAsync(nev);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MenhelyServiceReference.IOrokbefogadasKezelo")]
    public interface IOrokbefogadasKezelo {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrokbefogadasKezelo/OrokbefogadasElfogadasa", ReplyAction="http://tempuri.org/IOrokbefogadasKezelo/OrokbefogadasElfogadasaResponse")]
        void OrokbefogadasElfogadasa(Menhely.MenhelyServiceReference.Allat allat);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrokbefogadasKezelo/OrokbefogadasElfogadasa", ReplyAction="http://tempuri.org/IOrokbefogadasKezelo/OrokbefogadasElfogadasaResponse")]
        System.Threading.Tasks.Task OrokbefogadasElfogadasaAsync(Menhely.MenhelyServiceReference.Allat allat);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrokbefogadasKezelo/OrokbefogadasVisszautasitas", ReplyAction="http://tempuri.org/IOrokbefogadasKezelo/OrokbefogadasVisszautasitasResponse")]
        void OrokbefogadasVisszautasitas(Menhely.MenhelyServiceReference.Allat allat);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrokbefogadasKezelo/OrokbefogadasVisszautasitas", ReplyAction="http://tempuri.org/IOrokbefogadasKezelo/OrokbefogadasVisszautasitasResponse")]
        System.Threading.Tasks.Task OrokbefogadasVisszautasitasAsync(Menhely.MenhelyServiceReference.Allat allat);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrokbefogadasKezelo/KerelemLeadas", ReplyAction="http://tempuri.org/IOrokbefogadasKezelo/KerelemLeadasResponse")]
        void KerelemLeadas(Menhely.MenhelyServiceReference.Orokbefogado orokbefogado, Menhely.MenhelyServiceReference.Allat allat);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrokbefogadasKezelo/KerelemLeadas", ReplyAction="http://tempuri.org/IOrokbefogadasKezelo/KerelemLeadasResponse")]
        System.Threading.Tasks.Task KerelemLeadasAsync(Menhely.MenhelyServiceReference.Orokbefogado orokbefogado, Menhely.MenhelyServiceReference.Allat allat);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IOrokbefogadasKezeloChannel : Menhely.MenhelyServiceReference.IOrokbefogadasKezelo, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OrokbefogadasKezeloClient : System.ServiceModel.ClientBase<Menhely.MenhelyServiceReference.IOrokbefogadasKezelo>, Menhely.MenhelyServiceReference.IOrokbefogadasKezelo {
        
        public OrokbefogadasKezeloClient() {
        }
        
        public OrokbefogadasKezeloClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public OrokbefogadasKezeloClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OrokbefogadasKezeloClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OrokbefogadasKezeloClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void OrokbefogadasElfogadasa(Menhely.MenhelyServiceReference.Allat allat) {
            base.Channel.OrokbefogadasElfogadasa(allat);
        }
        
        public System.Threading.Tasks.Task OrokbefogadasElfogadasaAsync(Menhely.MenhelyServiceReference.Allat allat) {
            return base.Channel.OrokbefogadasElfogadasaAsync(allat);
        }
        
        public void OrokbefogadasVisszautasitas(Menhely.MenhelyServiceReference.Allat allat) {
            base.Channel.OrokbefogadasVisszautasitas(allat);
        }
        
        public System.Threading.Tasks.Task OrokbefogadasVisszautasitasAsync(Menhely.MenhelyServiceReference.Allat allat) {
            return base.Channel.OrokbefogadasVisszautasitasAsync(allat);
        }
        
        public void KerelemLeadas(Menhely.MenhelyServiceReference.Orokbefogado orokbefogado, Menhely.MenhelyServiceReference.Allat allat) {
            base.Channel.KerelemLeadas(orokbefogado, allat);
        }
        
        public System.Threading.Tasks.Task KerelemLeadasAsync(Menhely.MenhelyServiceReference.Orokbefogado orokbefogado, Menhely.MenhelyServiceReference.Allat allat) {
            return base.Channel.KerelemLeadasAsync(orokbefogado, allat);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MenhelyServiceReference.ITelephelyKezelo")]
    public interface ITelephelyKezelo {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITelephelyKezelo/TelephelyFelvetel", ReplyAction="http://tempuri.org/ITelephelyKezelo/TelephelyFelvetelResponse")]
        void TelephelyFelvetel(string cim);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITelephelyKezelo/TelephelyFelvetel", ReplyAction="http://tempuri.org/ITelephelyKezelo/TelephelyFelvetelResponse")]
        System.Threading.Tasks.Task TelephelyFelvetelAsync(string cim);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITelephelyKezelo/KetrecHozzaadas", ReplyAction="http://tempuri.org/ITelephelyKezelo/KetrecHozzaadasResponse")]
        void KetrecHozzaadas(Menhely.MenhelyServiceReference.Telephely telephely, int ketrecMeret, Menhely.MenhelyServiceReference.AllatFaj faj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITelephelyKezelo/KetrecHozzaadas", ReplyAction="http://tempuri.org/ITelephelyKezelo/KetrecHozzaadasResponse")]
        System.Threading.Tasks.Task KetrecHozzaadasAsync(Menhely.MenhelyServiceReference.Telephely telephely, int ketrecMeret, Menhely.MenhelyServiceReference.AllatFaj faj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITelephelyKezelo/KetrecTorles", ReplyAction="http://tempuri.org/ITelephelyKezelo/KetrecTorlesResponse")]
        void KetrecTorles(Menhely.MenhelyServiceReference.Telephely telephely, Menhely.MenhelyServiceReference.Ketrec ketrec);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITelephelyKezelo/KetrecTorles", ReplyAction="http://tempuri.org/ITelephelyKezelo/KetrecTorlesResponse")]
        System.Threading.Tasks.Task KetrecTorlesAsync(Menhely.MenhelyServiceReference.Telephely telephely, Menhely.MenhelyServiceReference.Ketrec ketrec);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITelephelyKezelo/KetrecModositas", ReplyAction="http://tempuri.org/ITelephelyKezelo/KetrecModositasResponse")]
        void KetrecModositas(Menhely.MenhelyServiceReference.Ketrec ketrec);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITelephelyKezelo/KetrecModositas", ReplyAction="http://tempuri.org/ITelephelyKezelo/KetrecModositasResponse")]
        System.Threading.Tasks.Task KetrecModositasAsync(Menhely.MenhelyServiceReference.Ketrec ketrec);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITelephelyKezelo/TelephelyTorles", ReplyAction="http://tempuri.org/ITelephelyKezelo/TelephelyTorlesResponse")]
        void TelephelyTorles(Menhely.MenhelyServiceReference.Telephely telephely);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITelephelyKezelo/TelephelyTorles", ReplyAction="http://tempuri.org/ITelephelyKezelo/TelephelyTorlesResponse")]
        System.Threading.Tasks.Task TelephelyTorlesAsync(Menhely.MenhelyServiceReference.Telephely telephely);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITelephelyKezelo/AllatMasikTelephelyre", ReplyAction="http://tempuri.org/ITelephelyKezelo/AllatMasikTelephelyreResponse")]
        void AllatMasikTelephelyre(Menhely.MenhelyServiceReference.Allat allat, Menhely.MenhelyServiceReference.Telephely hovaTelep, Menhely.MenhelyServiceReference.Ketrec hovaKetrec);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITelephelyKezelo/AllatMasikTelephelyre", ReplyAction="http://tempuri.org/ITelephelyKezelo/AllatMasikTelephelyreResponse")]
        System.Threading.Tasks.Task AllatMasikTelephelyreAsync(Menhely.MenhelyServiceReference.Allat allat, Menhely.MenhelyServiceReference.Telephely hovaTelep, Menhely.MenhelyServiceReference.Ketrec hovaKetrec);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITelephelyKezelo/TelephelyListazas", ReplyAction="http://tempuri.org/ITelephelyKezelo/TelephelyListazasResponse")]
        Menhely.MenhelyServiceReference.Telephely[] TelephelyListazas();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITelephelyKezelo/TelephelyListazas", ReplyAction="http://tempuri.org/ITelephelyKezelo/TelephelyListazasResponse")]
        System.Threading.Tasks.Task<Menhely.MenhelyServiceReference.Telephely[]> TelephelyListazasAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITelephelyKezelo/TelephelyListazasEgy", ReplyAction="http://tempuri.org/ITelephelyKezelo/TelephelyListazasEgyResponse")]
        Menhely.MenhelyServiceReference.Telephely[] TelephelyListazasEgy(string cim);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITelephelyKezelo/TelephelyListazasEgy", ReplyAction="http://tempuri.org/ITelephelyKezelo/TelephelyListazasEgyResponse")]
        System.Threading.Tasks.Task<Menhely.MenhelyServiceReference.Telephely[]> TelephelyListazasEgyAsync(string cim);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITelephelyKezelo/KetrecListazas", ReplyAction="http://tempuri.org/ITelephelyKezelo/KetrecListazasResponse")]
        Menhely.MenhelyServiceReference.Ketrec[] KetrecListazas();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITelephelyKezelo/KetrecListazas", ReplyAction="http://tempuri.org/ITelephelyKezelo/KetrecListazasResponse")]
        System.Threading.Tasks.Task<Menhely.MenhelyServiceReference.Ketrec[]> KetrecListazasAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITelephelyKezelo/KetrecListazasEgy", ReplyAction="http://tempuri.org/ITelephelyKezelo/KetrecListazasEgyResponse")]
        Menhely.MenhelyServiceReference.Ketrec[] KetrecListazasEgy(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITelephelyKezelo/KetrecListazasEgy", ReplyAction="http://tempuri.org/ITelephelyKezelo/KetrecListazasEgyResponse")]
        System.Threading.Tasks.Task<Menhely.MenhelyServiceReference.Ketrec[]> KetrecListazasEgyAsync(int id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITelephelyKezeloChannel : Menhely.MenhelyServiceReference.ITelephelyKezelo, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TelephelyKezeloClient : System.ServiceModel.ClientBase<Menhely.MenhelyServiceReference.ITelephelyKezelo>, Menhely.MenhelyServiceReference.ITelephelyKezelo {
        
        public TelephelyKezeloClient() {
        }
        
        public TelephelyKezeloClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TelephelyKezeloClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TelephelyKezeloClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TelephelyKezeloClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void TelephelyFelvetel(string cim) {
            base.Channel.TelephelyFelvetel(cim);
        }
        
        public System.Threading.Tasks.Task TelephelyFelvetelAsync(string cim) {
            return base.Channel.TelephelyFelvetelAsync(cim);
        }
        
        public void KetrecHozzaadas(Menhely.MenhelyServiceReference.Telephely telephely, int ketrecMeret, Menhely.MenhelyServiceReference.AllatFaj faj) {
            base.Channel.KetrecHozzaadas(telephely, ketrecMeret, faj);
        }
        
        public System.Threading.Tasks.Task KetrecHozzaadasAsync(Menhely.MenhelyServiceReference.Telephely telephely, int ketrecMeret, Menhely.MenhelyServiceReference.AllatFaj faj) {
            return base.Channel.KetrecHozzaadasAsync(telephely, ketrecMeret, faj);
        }
        
        public void KetrecTorles(Menhely.MenhelyServiceReference.Telephely telephely, Menhely.MenhelyServiceReference.Ketrec ketrec) {
            base.Channel.KetrecTorles(telephely, ketrec);
        }
        
        public System.Threading.Tasks.Task KetrecTorlesAsync(Menhely.MenhelyServiceReference.Telephely telephely, Menhely.MenhelyServiceReference.Ketrec ketrec) {
            return base.Channel.KetrecTorlesAsync(telephely, ketrec);
        }
        
        public void KetrecModositas(Menhely.MenhelyServiceReference.Ketrec ketrec) {
            base.Channel.KetrecModositas(ketrec);
        }
        
        public System.Threading.Tasks.Task KetrecModositasAsync(Menhely.MenhelyServiceReference.Ketrec ketrec) {
            return base.Channel.KetrecModositasAsync(ketrec);
        }
        
        public void TelephelyTorles(Menhely.MenhelyServiceReference.Telephely telephely) {
            base.Channel.TelephelyTorles(telephely);
        }
        
        public System.Threading.Tasks.Task TelephelyTorlesAsync(Menhely.MenhelyServiceReference.Telephely telephely) {
            return base.Channel.TelephelyTorlesAsync(telephely);
        }
        
        public void AllatMasikTelephelyre(Menhely.MenhelyServiceReference.Allat allat, Menhely.MenhelyServiceReference.Telephely hovaTelep, Menhely.MenhelyServiceReference.Ketrec hovaKetrec) {
            base.Channel.AllatMasikTelephelyre(allat, hovaTelep, hovaKetrec);
        }
        
        public System.Threading.Tasks.Task AllatMasikTelephelyreAsync(Menhely.MenhelyServiceReference.Allat allat, Menhely.MenhelyServiceReference.Telephely hovaTelep, Menhely.MenhelyServiceReference.Ketrec hovaKetrec) {
            return base.Channel.AllatMasikTelephelyreAsync(allat, hovaTelep, hovaKetrec);
        }
        
        public Menhely.MenhelyServiceReference.Telephely[] TelephelyListazas() {
            return base.Channel.TelephelyListazas();
        }
        
        public System.Threading.Tasks.Task<Menhely.MenhelyServiceReference.Telephely[]> TelephelyListazasAsync() {
            return base.Channel.TelephelyListazasAsync();
        }
        
        public Menhely.MenhelyServiceReference.Telephely[] TelephelyListazasEgy(string cim) {
            return base.Channel.TelephelyListazasEgy(cim);
        }
        
        public System.Threading.Tasks.Task<Menhely.MenhelyServiceReference.Telephely[]> TelephelyListazasEgyAsync(string cim) {
            return base.Channel.TelephelyListazasEgyAsync(cim);
        }
        
        public Menhely.MenhelyServiceReference.Ketrec[] KetrecListazas() {
            return base.Channel.KetrecListazas();
        }
        
        public System.Threading.Tasks.Task<Menhely.MenhelyServiceReference.Ketrec[]> KetrecListazasAsync() {
            return base.Channel.KetrecListazasAsync();
        }
        
        public Menhely.MenhelyServiceReference.Ketrec[] KetrecListazasEgy(int id) {
            return base.Channel.KetrecListazasEgy(id);
        }
        
        public System.Threading.Tasks.Task<Menhely.MenhelyServiceReference.Ketrec[]> KetrecListazasEgyAsync(int id) {
            return base.Channel.KetrecListazasEgyAsync(id);
        }
    }
}
